### ISSUE TITLE
BUG - Cannot build on Linux due to case sensitivity

### ISSUE THREAD

**Issue by amugofjava** [moda20/flutter-tunein#2]
**Describe the bug**
Hi. Trying to build on Linux fails with the following error:

```
lib/services/routes/pageRoutes.dart:4:8: Error: Error when reading 'lib/components/Tune/SongTags.dart': No such file or directory
import 'package:Tunein/components/Tune/SongTags.dart'; 
```
This is because the file is called songTags.dart and not SongTags.dart. I guess you must build your code on Windows?

**To Reproduce**

1. Clone the repo on a Linux machine (and I guess this would work on Mac too).
2. Do a `flutter run`

App fails to build.

**Expected behavior**

The imports should match the same case as the files.

**Screenshots**
![tunein-bug1](https://user-images.githubusercontent.com/5526902/97806726-fb11a400-1c54-11eb-9414-1926060dbe64.png)

**Smartphone (please complete the following information):**
 - Linux PC - Ubuntu 20.04
 - Attempting to run on an emulator

**Comment by moda20** [comment]
Hi @amugofjava ,
yes, that is very weird, I can assure you it works on macOS. but the problem is that most of the imports are handled by Android studio.
I pushed a commit to fix this issue. Please try to build again and tell me if it works.

**Comment by amugofjava** [comment]
I've pulled the change and that fixed the case issue; however, I am now getting errors around the preload_pageview_plugin. I've done a `flutter clean` and rebuilt, but I still get these errors:

```
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:250:21: Error: The getter 'hasViewportDimension' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasViewportDimension'.
    return page * ((hasViewportDimension == true) ? viewportDimension : 0) * viewportFraction;
                    ^^^^^^^^^^^^^^^^^^^^                                
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:254:23: Error: The getter 'hasPixels' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasPixels'.
  double get page => (hasPixels == false)                               
                      ^^^^^^^^^                                         
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:257:19: Error: The getter 'hasContentDimensions' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasContentDimensions'.
    pixels.clamp((hasContentDimensions == true) ? minScrollExtent : null, (hasContentDimensions == true) ? maxScrollExtent : null),
                  ^^^^^^^^^^^^^^^^^^^^                                  
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:257:76: Error: The getter 'hasContentDimensions' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasContentDimensions'.
    pixels.clamp((hasContentDimensions == true) ? minScrollExtent : null, (hasContentDimensions == true) ? maxScrollExtent : null),
                                                                           ^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:258:6: Error: The getter 'hasViewportDimension' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasViewportDimension'.
    (hasViewportDimension == true) ? viewportDimension : null,          
     ^^^^^^^^^^^^^^^^^^^^                                               
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:264:65: Error: The getter 'hasPixels' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasPixels'.
        ?.writeState(context.storageContext, getPageFromPixels((hasPixels) ? pixels : null, (hasViewportDimension) ? viewportDimension : null));
                                                                ^^^^^^^^^
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:264:94: Error: The getter 'hasViewportDimension' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasViewportDimension'.
        ?.writeState(context.storageContext, getPageFromPixels((hasPixels) ? pixels : null, (hasViewportDimension) ? viewportDimension : null));
                                                                                             ^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:269:9: Error: The getter 'hasPixels' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasPixels'.
    if (hasPixels == true) {                                            
        ^^^^^^^^^                                                       
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:277:43: Error: The getter 'hasViewportDimension' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasViewportDimension'.
    final double oldViewportDimensions = (hasViewportDimension) ? this.viewportDimension : null;
                                          ^^^^^^^^^^^^^^^^^^^^          
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:279:31: Error: The getter 'hasPixels' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasPixels'.
    final double oldPixels = (hasPixels) ? pixels : null;               
                              ^^^^^^^^^                                 
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:299:45: Error: The getter 'hasContentDimensions' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasContentDimensions'.
      minScrollExtent: minScrollExtent ?? ((hasContentDimensions) ? this.minScrollExtent : null),
                                            ^^^^^^^^^^^^^^^^^^^^        
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:300:45: Error: The getter 'hasContentDimensions' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasContentDimensions'.
      maxScrollExtent: maxScrollExtent ?? ((hasContentDimensions) ? this.maxScrollExtent : null),
                                            ^^^^^^^^^^^^^^^^^^^^        
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:301:27: Error: The getter 'hasPixels' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasPixels'.
      pixels: pixels ?? ((hasPixels) ? this.pixels : null),             
                          ^^^^^^^^^                                     
../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart:302:49: Error: The getter 'hasViewportDimension' isn't defined for the class '_PagePosition'.
 - '_PagePosition' is from 'package:preload_page_view/preload_page_view.dart' ('../../flutter/.pub-cache/git/preload_page_view-508c0ef34dd0c0aba7536bc0d79f34a92195535e/lib/preload_page_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'hasViewportDimension'.
      viewportDimension: viewportDimension ?? ((hasViewportDimension) ? this.viewportDimension : null),
                                                ^^^^^^^^^^^^^^^^^^^^    
                                                                        
                                                                        
FAILURE: Build failed with an exception. 
```

**Comment by moda20** [comment]
@amugofjava  Please post your flutter doctor output here. Also, this problem is related to another package, i am looking at it right now.
It appears you will need a certain version of flutter that has the missing `hasViewportDimension` variable. I am running all of this on the master branch: Flutter (Channel master, 1.24.0-2.0.pre.95, on Mac OS X 10.15.5 19F96 darwin-x64, locale en)


If you don't want to switch the flutter branch, you can change the reference of the `preload_page_view` dependency like the following : 
```yaml
  preload_page_view:
    git:
      url: https://github.com/moda20/preload_page_view
      ref: 90bf545d49c79cb4980db3cf396e87a7e4b26f58
```
this will get you the old version of the lib `preload_page_view` that would not have the issue you encountered.

**Comment by amugofjava** [comment]
That makes sense then as I am running on Flutter stable.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_GB.UTF-8)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by amugofjava** [comment]
OK, using that git ref fixed the issue and I can now compile and run. I'll give it a spin!

**Comment by moda20** [comment]
@amugofjava great, thanks. don't forget to tell me what you think.
